### ISSUE TITLE
关于代码中使用了中文导致无法编译的问题

### ISSUE THREAD

**Issue by MrLuuuu** [busyluo/NetAssistant#2]
你好，我克隆了你的代码并尝试使用QtCreater编译它，发现一直报出C2001和C2143的错误，经检查发现是因为你的代码中使用了中文，导致编码格式错误，建议你在mainwindow.cpp文件开头部分加上一句如下代码
`# pragma execution_character_set("utf-8")`
    通过添加这行代码我已经成功编译并运行了你的代码

**Comment by busyluo** [comment]
是用MSVC编译的吧？我没测试过这个。我看了下是msvc支持带bom的utf8，已经添加了。
