### ISSUE TITLE
ubuntu 18.04 下中文部分乱码

### ISSUE THREAD

**Issue by ArtisticZhao** [busyluo/NetAssistant#4]
您好: 
这个网络助手在Linux下十分好用, 但是在我的ubuntu18.04下出现了中文部分乱码问题.
我录制了一个gif来展示问题
![na_ch_error](https://user-images.githubusercontent.com/22850287/103748721-80437b80-503f-11eb-8e27-9b42c17d14b3.gif)
祝好

**Comment by busyluo** [comment]
很遗憾没有复现。
![image](https://user-images.githubusercontent.com/16347811/103843525-f3e29880-50d2-11eb-9184-b1068f43f45e.png)

环境如下：
![image](https://user-images.githubusercontent.com/16347811/103843205-6141f980-50d2-11eb-904f-5fb2aa8dd51e.png)

麻烦提供下更详细的情况。

**Comment by ArtisticZhao** [comment]
![image](https://user-images.githubusercontent.com/22850287/103846571-5fc7ff80-50d9-11eb-9fa3-12a7a372a745.png)
系统和工具的详情如上图.
我的系统是安装的英文版, 不知道与这个十分有关. 或者我应该升级qt到qt5?
谢谢.

**Comment by ArtisticZhao** [comment]
确实应该是qt4跟qt5的问题, 之前没有注意qt版本进行的编译. 换成qt5就没有这个问题了!
```
make clean
qmake -qt=qt5 NetAssistant.pro
make
```
