### ISSUE TITLE
AUR NetAssistant 安装包

### ISSUE THREAD

**Issue by taotieren** [busyluo/NetAssistant#5]
将 NetAssistant 打包到 AUR 仓库了，方便 Arch 系用户下载安装更新：

发行版：[AUR NetAssistant](https://aur.archlinux.org/packages/netassistant/)
开发版：[AUR NetAssistant-git](https://aur.archlinux.org/packages/netassistant-git/)

**Comment by luokyme** [comment]
好样的。
